config/routes.rb
Rails.application.routes.draw do
  # 分三層
  # 第一層：public

  resources :cates
  resources :items do
    member do
      get :add_cart
    end
  end


  devise_for :managers
  devise_for :users


  root "items#index"

  # 第一層：購物車
  resources :items, :only => [:index, :show]

  # 上面的網址：
  # /statics/action/
  #
  # namespace裡面的網址：
  # dashboard/items/action


  # 第二層：dashboard
  namespace :dashboard do
    resources :orders

    # 第三層：admin
    namespace :admin do
      #現在是教學示例，建議:admin寫成亂碼，像是:sakwejh，這樣才不會被猜到
      # 一個系統在打時，建議從後面打到前面，例如先從管理介面開始打
      resources :items  # 要賣的東西
      resources :cates  # 要賣的東西的分類
      resources :orders # 訂單
      resources :users
      resources :managers
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cate.rb
class Cate < ApplicationRecord
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :cate
  has_attached_file :cover,
   styles: {
     original: "1024x1024>",
     cover: "300x300>",
     icon: "150x150#"
    },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable#, :registerable,
         #:recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_item
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable
         #:recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cates_controller.rb
class CatesController < ApplicationController
  before_action :set_cate, only: [:show, :edit, :update, :destroy]

  # GET /cates
  def index
    @cates = Cate.all
  end

  # GET /cates/1
  def show
  end

  # GET /cates/new
  def new
    @cate = Cate.new
  end

  # GET /cates/1/edit
  def edit
  end

  # POST /cates
  def create
    @cate = Cate.new(cate_params)

    if @cate.save
      redirect_to @cate, notice: 'Cate was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cates/1
  def update
    if @cate.update(cate_params)
      redirect_to @cate, notice: 'Cate was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cates/1
  def destroy
    @cate.destroy
    redirect_to cates_url, notice: 'Cate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cate
      @cate = Cate.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cate_params
      params.fetch(:cate, {})
    end
end

app/controllers/dashboard/admin/admin_controller.rb
class Dashboard::Admin::AdminController < ApplicationController
  before_action :authenticate_manager!
  layout "admin"
end

app/controllers/dashboard/admin/cates_controller.rb
class Dashboard::Admin::CatesController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/admin/items_controller.rb
class Dashboard::Admin::ItemsController < Dashboard::Admin::AdminController
  def index
    @items = @paginate = Item.includes(:cate).order("id DESC").paginate(:page => params[:page])
  end
  def new
    @item = Item.new
  end
  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end
  # POST /items
  def create
    @item = Item.new(item_params)
    if @item.save!
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end
  # PATCH/PUT /items/1
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to :action => :index , notice: 'Item was successfully updated.'
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit!
    end
end

app/controllers/dashboard/admin/orders_controller.rb
class Dashboard::Admin::OrdersController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/admin/users_controller.rb
class Dashboard::Admin::UsersController < Dashboard::Admin::AdminController

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::DashboardController
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def add_cart
    session[:cart] ||= {}
    item = Item.where(:id => params[:id]).first
    if item
      key = item.id.to_s
      session[:cart][key] ||= 0
      session[:cart][key] += 1
    end
    render :json => {:counter => session[:cart].length}.to_json
  end
  # GET /items
  def index
    @items = @paginate = Item.includes(:cate).order("id DESC").paginate(:page => params[:page])
  end

  def show
    @item = Item.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_cart_count
    if session[:cart]
      return session[:cart].length
    else
      return 0
    end
  end

end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <h1>後台頁面:admin</h1>

      hi! <%= current_manager.email %> , <%= link_to "登出" , destroy_manager_session_path ,:method => "delete" %>

    <hr/>

    <ul>
      <li><%= link_to "商品管理" , dashboard_admin_items_path %></li>
    </ul>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

    <%= yield %>

    <hr/>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= yield :header %>
  </head>

  <body>

    <h1>對外頁面:public</h1>
    <div>購物車數量：<span id="cart_counter"><%= get_cart_count %></span></div>
    <%= session[:cart] %>

    <% if current_user %>
      hi! <%= current_user.email %>
      <%= link_to "登出" , destroy_user_session_path ,:method => "delete" %>
    <% else %>
      <%= link_to "登入" , new_user_session_path %> , <%= link_to "註冊" , new_user_registration_path %>
    <% end %>

    <hr/>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

    <%= yield %>

    <hr/>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <h1>使用者後台:dashboard</h1>

      hi! <%= current_user.email %> , <%= link_to "登出" , destroy_user_session_path ,:method => "delete" %>

    <hr/>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

    <%= yield %>

    <hr/>

    <%= will_paginate @paginate if @paginate %>

    <hr/>

  </body>
</html>